query ($username: String!, $password: String!) {
  userAuthenticate(username: $username, password: $password) {
    token
    user {
      id
      username
      roles {
        name
      }
    }
  }
}
