mutation ($passwordResetRequestId: String!, $password: String!) {
  userResetPassword(passwordResetId: $passwordResetRequestId, password: $password) {
    token
    user {
      id
      username
      roles {
        name
      }
    }
  }
}
