mutation ($username: String!, $password: String) {
  userCreate(username: $username, password: $password) {
    token
    user {
      id
      username
      roles {
        name
      }
    }
  }
}
